version: '3.8'

services:
  backend:
    build: .
    container_name: quizzy-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+pymysql://root:abcd@mysql:3306/quizzy
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    networks:
      - quizzy-net

  mysql:
    image: mysql:8.0
    container_name: quizzy-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abcd
      - MYSQL_DATABASE=quizzy
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - quizzy-net

volumes:
  mysql_data:

networks:
  quizzy-net:
    driver: bridge 