version: '3.8'

services:
  backend:
    build: .
    container_name: quizzy-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:123321@mysql:3306/BlogApplication
    depends_on:
      - mysql
    networks:
      - quizzy-net

  mysql:
    image: mysql:8.0
    container_name: quizzy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123321
      MYSQL_DATABASE: BlogApplication
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - quizzy-net

volumes:
  mysql_data:

networks:
  quizzy-net:
    driver: bridge 